config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end
  root 'posts#index'

  post 'markdown/preview'

  get '/about', to: 'pages#about'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end
end

app/controllers/markdown_controller.rb
class MarkdownController < ApplicationController
  def preview
    @text = params[:data]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true,
      space_after_headers: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= markdown(comment.body) %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %></p>
  </div>

  <% if user_signed_in? %>
  <p><%= link_to 'Delete', [comment.post, comment],
                  method: :delete, class: "button",
                  data: { confirm: 'Are you sure?' } %>
  </p>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body, html: { cols: "80", rows: "20"} %>
  </p>
  <br>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="google-site-verification" content="zE_ePLd_IQJMfYabI01FvG2iwgPEl9KO82kMdADbUqs" />
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="sidebar">
    <div id="logo">
      <%= link_to root_path do %>
        <%= image_tag "logo.svg" %>
      <% end %>
    </div>

    <ul>
      <li class="category">Website</li>
      <li><%= link_to "Blog", root_path %></li>
      <li><%= link_to "About", about_path %></li>
    </ul>

    <ul>
      <li class="category">Social</li>
      <li><a href="https://twitter.com/AlexKalinoff">Twitter</a></li>
      <li><a href="https://github.com/Hunk13">Github</a></li>
      <li><a href="http://kalinka.pw">Curriculum Vitae</a></li>
      <li><a href="mailto:info@kalinka.pw">Email</a></li>
    </ul>

    <% if !user_signed_in? %>
      <p class="sign_in">Admin LogIn</p>
    <% end %>
  </div>

  <div id="main_content">
    <div id="header">
      <% if current_page?(root_path) %>
        <p>All Posts</p>
      <% elsif current_page?(about_path) %>
        <p>About</p>
      <% else %>
        <%= link_to "Back to all posts", root_path %>
      <% end %>

      <% if user_signed_in? %>
        <div class="buttons">
           <button class="button"><%= link_to "New Post", new_post_path %></button>
           <button class="button"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></button>
        </div>
      <% else %>
         <div class="buttons">
           <button class="button"><%= link_to "Sign Up", new_user_registration_path %></button>
           <button class="button"><%= link_to "Sign In", new_user_session_path %></button>
        </div>
      <% end %>
    </div>

    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert") %>
    <% end %>

    <%= yield %>

  </div>

<% if Rails.env.production? %>
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter21077476 = new Ya.Metrika({
                    id:21077476,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/21077476" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
<% end %>

</body>
</html>

app/views/markdown/preview.html.erb
<%= markdown(@text) %>

app/views/pages/about.html.erb
<div id="page_wrapper">
  <div id="profile_image">
    <%= image_tag('profile.jpeg') %>
  </div>

  <div id="content">
    <h1>Hey, I'm Aleksandr Kainka</h1>
    <p>I'm a junior Ruby and Ruby on Rails developer, this website was created using the following technology stack:</p>
    <ul>
        <li>Programming language: Ruby</li>
        <li>Framework: Ruby on Rails</li>
        <li>Database: PostgreSQL</li>
        <li>Server: Linux Ubuntu 14.04</li>
        <li>Web server: Nginx</li>
        <li>The Rails Server: Puma</li>
        <li>Deployment: Capistrano</li>
    </ul>
    <p>Always ready to cooperate as a freelancer or full-time.</p>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
<h1>Edit post</h1>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"><%= link_to post.title, post %></h2>
    <p class="date"><%= post.created_at.strftime("%B, %d, %Y") %></p>
  </div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
<h1>New post</h1>
  <%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
      <div id="errors">
        <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title">
    <%= @post.title %>
  </h1>

  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> Ago
    <% if user_signed_in? %>
      | <%= link_to 'Edit', edit_post_path(@post) %>
      | <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
  </p>

  <p class="body">
    <%= markdown(@post.body) %>
  </p>

  <div id="comments">
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>

    <% if user_signed_in? %>
      <h3>Add a comment:</h3>
      <%= render "comments/form" %>
    <% else %>
      <h3>That would leave a comment, you need to <%= link_to "register", new_user_registration_path %> or <%= link_to "log in", new_user_session_path %> with your data.</h3>
    <% end %>
  </div>
</div>